"""Meal plan service — BMR/TDEE calculation, Granite generation, Cloudant persistence."""

import uuid
from datetime import datetime, timezone

import structlog

from backend.api.config import settings
from backend.database.cloudant import cloudant_client
from backend.models.meal_plan import (
    DailyNutritionSummary,
    Meal,
    MealPlanRequest,
    MealPlanResponse,
)
from backend.prompts.meal_plan_prompt import build_meal_plan_prompt, parse_meal_plan_json
from backend.services.granite_service import generate_text

logger = structlog.get_logger(__name__)

_MEALS_DB = settings.CLOUDANT_DB_MEALS

# Activity multipliers keyed to Lifestyle enum values
_ACTIVITY_MULTIPLIERS: dict[str, float] = {
    "sedentary": 1.2,
    "lightly_active": 1.375,
    "moderately_active": 1.55,
    "very_active": 1.725,
    "extra_active": 1.9,
}

# Goal calorie adjustments (kcal relative to TDEE)
_GOAL_ADJUSTMENTS: dict[str, int] = {
    "weight_loss": -500,
    "maintenance": 0,
    "weight_gain": 300,
    "muscle_gain": 250,
}


def calculate_tdee(
    age: int,
    height_cm: float,
    weight_kg: float,
    gender: str,
    lifestyle: str,
    goal: str,
) -> int:
    """
    Compute Total Daily Energy Expenditure using the Mifflin-St Jeor equation.

    Formula:
        Male   BMR = 10·W + 6.25·H − 5·A + 5
        Female BMR = 10·W + 6.25·H − 5·A − 161

    Returns:
        Integer calorie target adjusted for goal.
    """
    if gender == "male":
        bmr = 10 * weight_kg + 6.25 * height_cm - 5 * age + 5
    else:
        bmr = 10 * weight_kg + 6.25 * height_cm - 5 * age - 161

    multiplier = _ACTIVITY_MULTIPLIERS.get(lifestyle, 1.2)
    tdee = bmr * multiplier
    adjustment = _GOAL_ADJUSTMENTS.get(goal, 0)
    return max(1200, round(tdee + adjustment))


def _parse_meal(data: dict) -> Meal:
    """Convert a raw dict from JSON into a validated Meal object."""
    return Meal(
        name=data.get("name", "Unnamed meal"),
        ingredients=data.get("ingredients", []),
        calories=int(data.get("calories", 0)),
        protein_g=float(data.get("protein_g", 0)),
        carbs_g=float(data.get("carbs_g", 0)),
        fat_g=float(data.get("fat_g", 0)),
        preparation_time_minutes=int(data.get("preparation_time_minutes", 15)),
        instructions=data.get("instructions", ""),
        explanation=data.get("explanation", ""),
    )


def _parse_nutrition_summary(data: dict, target_calories: int) -> DailyNutritionSummary:
    """Build a DailyNutritionSummary, falling back to target calories if missing."""
    return DailyNutritionSummary(
        total_calories=int(data.get("total_calories", target_calories)),
        protein_g=float(data.get("protein_g", 0)),
        carbs_g=float(data.get("carbs_g", 0)),
        fat_g=float(data.get("fat_g", 0)),
        fiber_g=float(data.get("fiber_g", 0)),
        water_ml=int(data.get("water_ml", 2500)),
    )


def generate_meal_plan(request: MealPlanRequest) -> MealPlanResponse:
    """
    Full pipeline:
      1. Calculate personalised calorie target (TDEE ± goal).
      2. Build the Granite prompt.
      3. Call Granite and parse the JSON response.
      4. Persist the generated plan to Cloudant.
      5. Return a MealPlanResponse.

    Raises:
        ValueError: if the model returns unparseable JSON.
        RuntimeError: propagated from granite_service on inference failure.
    """
    target_calories = calculate_tdee(
        age=request.age,
        height_cm=request.height_cm,
        weight_kg=request.weight_kg,
        gender=request.gender.value,
        lifestyle=request.lifestyle.value,
        goal=request.goal.value,
    )

    logger.info(
        "Generating meal plan",
        user_id=request.user_id,
        target_calories=target_calories,
        goal=request.goal.value,
    )

    prompt = build_meal_plan_prompt(
        age=request.age,
        height_cm=request.height_cm,
        weight_kg=request.weight_kg,
        gender=request.gender.value,
        goal=request.goal.value,
        diseases=request.diseases,
        allergies=request.allergies,
        cuisine_preference=request.cuisine_preference,
        budget_usd_per_day=request.budget_usd_per_day,
        lifestyle=request.lifestyle.value,
        target_calories=target_calories,
    )

    raw_output = generate_text(prompt)
    plan_data = parse_meal_plan_json(raw_output)

    breakfast = _parse_meal(plan_data.get("breakfast", {}))
    lunch = _parse_meal(plan_data.get("lunch", {}))
    dinner = _parse_meal(plan_data.get("dinner", {}))
    snacks = [_parse_meal(s) for s in plan_data.get("snacks", [])]
    nutrition_summary = _parse_nutrition_summary(
        plan_data.get("nutrition_summary", {}), target_calories
    )
    explanation = plan_data.get("explanation", "Personalised plan generated by NutriGenie AI.")

    response = MealPlanResponse(
        user_id=request.user_id,
        breakfast=breakfast,
        lunch=lunch,
        dinner=dinner,
        snacks=snacks,
        nutrition_summary=nutrition_summary,
        explanation=explanation,
    )

    _persist_plan(request.user_id, response, target_calories)
    return response


def _persist_plan(user_id: str, plan: MealPlanResponse, target_calories: int) -> None:
    """Store the generated meal plan document in Cloudant."""
    doc_id = str(uuid.uuid4())
    doc = {
        "_id": doc_id,
        "user_id": user_id,
        "target_calories": target_calories,
        "plan": plan.model_dump(mode="json"),
        "created_at": datetime.now(tz=timezone.utc).isoformat(),
    }
    cloudant_client.put_document(db=_MEALS_DB, doc_id=doc_id, document=doc)
    logger.info("Meal plan persisted", doc_id=doc_id, user_id=user_id)
